### PR TITLE
Doxygen comments

### PR DESCRIPTION
**Pull request by erincatto**
Cleaned up all doxygen comments in include directory.
Cleaned up SDF shaders for border thickness.
Joint reaction forces and sample with breakable joints.
User can adjust length units using b2SetLengthUnitsPerMeter
Simplified include files

### CODE REVIEW

**Comment by 1vanK** [comment]
Dots at ends of comments is not needed, it is automatically added when generating html (if corresponding setting is enabled)

**Comment by 1vanK** [comment]
```
typedef enum b2ShapeType
{
	/// A circle with an offset
	b2_circleShape,
```

can be

```
b2_circleShape, ///< A circle with an offset
```

instead

**Comment by erincatto** [comment]
> ```
> typedef enum b2ShapeType
> {
> 	/// A circle with an offset
> 	b2_circleShape,
> ```
> 
> can be
> 
> ```
> b2_circleShape, ///< A circle with an offset
> ```
> 
> instead

Yeah, I know this. I guess this is my preference. Do you think my style makes the code harder to read?

**Comment by 1vanK** [comment]
It's a matter of personal preference. There is no right or wrong style. I was just sharing information

**Pull request merged**
